### ISSUE TITLE
Service Unavailable but notice apparently got in publishing pipeline

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#46] opened 2020-05-19 14:13 UTC
We got error 
`ServiceUnavailable <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0522+XgAAAAAFd1mCfzTbRrcAldJkTDHbQlJVMzBFREdFMDQxNwAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=</span></div></div></body></html>.`
RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_19247?parentId=2019-024413&projectId=25128

and when retrying to publish we got error
`BadRequest Notice being updated is not a draft or publishedThenRejected. State=WaitingToBePublished.`
RequestUri: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_19247?parentId=2019-024413&projectId=25128

I hope that if error is given, notice will not be published. 

For this notice: no actions required as it already is published, it should stay as as such.

**Comment by jannef** [comment] 2020-05-20 05:31
We've encountered the same issue yesterday when developing a hotfix in staging (koulutus) environment. This error is raised when API-management does not recieve recieve http-response from upstream.

There was no clear cause for our issue, so it might have been Azure instability yesterdat afternoon.

**Comment by cloudia-jt** [comment] 2020-05-20 11:57
The other time that we've seen this error was back in 2020-01-09 12:45 but error does not have that fancy html error page. I'm guessing it's different issue.

**Comment by anttiremes** [comment] 2020-10-30 07:04
Same issue 
time: 2020-10-30 08:21:35.270
etsidentifier: production_27508

**Comment by anttiremes** [comment] 2020-10-30 07:05
And
time: 2020-10-28 08:18:49.640
etsidentifier: production_23178

**Comment by anttiremes** [comment] 2020-10-30 07:11
And

2020-10-29 13:56:04.167 etsidfixed_35231
2020-10-29 11:20:24.970 etsidfixed_35186
2020-10-29 11:06:37.287 production_22750
2020-10-29 18:01:48.973 production_35278
2020-10-29 12:27:14.400 etsidfixed_35198
2020-10-28 16:47:05.887 etsidfixed_35121

**Comment by AlexEngblom** [comment] 2020-10-30 08:56
Unfortunately we still haven't been able to pinpoint the root cause behind this issue within our api-management solution.
These cases seem to fall within this same problem.

You should be able to poll the GET api to get their data.

**Comment by jannef** [comment] 2020-11-13 08:13
The issue was been identified, earlier. The service bus upstream some times lags out, and causes the request to take unusual amounth of time. We are working on a fix.

**Comment by jannef** [comment] 2020-11-24 06:36
A fix for this issue was installed 23.11.2020, around 15:30.

Before, we were pushing gzipped notices to service bus for publication; and this operation some times took way too long. Now we are pushing some ids and download the xml-data as the message is being handled -- the timeout should be eliminated.

**Closed** 2020-11-26 08:58 UTC
