### ISSUE TITLE
Hilma sends notice to ted twice

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#103] opened 2021-04-01 09:05 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
etsidentifier: 

production_52170

![image-20210331-123405](https://user-images.githubusercontent.com/60220798/113270796-89f91a00-92e2-11eb-976e-41aa1c3f1fa5.png)
![kuva](https://user-images.githubusercontent.com/60220798/113270839-91202800-92e2-11eb-8555-2777fe1196e2.png)
**To Reproduce**
- API endpoint that the request was sent to
- HTTP method
- HTTP headers
- sample request payload

**Expected behavior**

**API response**
What is the response from Hilma API? Include the response headers and timestamps.

**Additional context**

**Comment by jannef** [comment] 2021-04-01 10:20
There indeed seems to be an issue with the given notice. TED has recieved this notice twice: at 14:00:54 (accepted) and then again at 14:01:57. I'll fix the notice by hand and look into this issue.

**Comment by jannef** [comment] 2021-04-01 10:26
The notice in Hilma is now set to track the correct TED submission and been set to correct state. Investigation the cause next.

**Comment by jannef** [comment] 2021-04-01 11:33
Few issues were detected investigating this issue:

1. Loggin was misconfigured. There was daily data ingestion cap set for the logging solution, causing afternoon logs to be trucated on busy days (The limit was configured to be reset daily in the evening.) This issue is resolved by removing data ingestion cap.
2. Due lack of logging, exact cause of this issue can not be determined. However, a likely cause was identified by analyzing the TED-integration source code.

-

**Comment by jannef** [comment] 2021-04-09 12:28
Fix will be installed as part of version update 21.04.2021

**Closed** 2021-04-23 10:52 UTC
Labels: bug
