### ISSUE TITLE
Ennakkoilmoitus - suorahankinta - ex ante - ilmoitus (TED F15) [noticeType=1500] disagreetobepublished

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#53] opened 2020-07-01 09:42 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**

**To Reproduce**
	"TotalValue": {
		"Type": 1,
		"Value": 560000.0,
		"Currency": "EUR",
		"DisagreeToBePublished": true
	},

					"FinalTotalValue": {
						"Type": 1,
						"Value": 560000.0,
						"Currency": "EUR",
						"DisagreeToBePublished": true

**Expected behavior**
Notice should be published

**API response**
BadRequest The notice cannot be published to TED: Value disagreeToBePublished == true for notice.TotalValue is not valid for notice type ExAnte, Value disagreeToBePublished == true for notice.ObjectDescriptions[0].AwardContract.AwardedContract.FinalTotalValue is not valid for notice type ExAnte.

**Additional context**

**Comment by jannef** [comment] 2020-07-01 09:58
The API is working as intended.  The publication of the final value cannot be prevented on F15, no matter which legal basis is used.

**Comment by jannef** [comment] 2020-07-01 10:04
The option should only be valid for legal basis 2014/25/EU. Investigating,







T

**Comment by jannef** [comment] 2020-07-01 10:23
A bug has been identified in the validation code, giving a false positive error. The fix is being worked.

**Comment by jannef** [comment] 2020-07-01 11:01
There is a fix pending for deployment. The fix will be deployed later today -- we are waiting to see if we can manage to fit another fix into same deployment.

**Comment by jannef** [comment] 2020-07-01 13:17
Fix has been deployed. The notice should be safe to re-try now.

**Closed** 2020-07-03 10:22 UTC
Labels: solved
