### ISSUE TITLE
F17 Internal server error

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#13] opened 2020-02-19 13:44 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
TED F17 POST validation test gives response 200 OK. PUT gives 500 Internal Server Error.

**To Reproduce**
- API endpoint that the request was sent to
PUT: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/production_5813
POST: https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/test_202002191530
- sample request payload
``` json
{
	"LegalBasis": "32009L0081",
	"CommunicationInformation": {
		"ProcurementDocumentsUrl": "https://fooo.bar/asdf",
		"AdditionalInformation": 1,
		"AdditionalInformationAddress": {
			"OfficialName": "Lorem ipsum dolor sit amet",
			"NationalRegistrationNumber": "2012703-3",
			"PostalAddress": {
				"StreetAddress": "Nullam velit nisl, eleifend 2324",
				"PostalCode": "00002",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "fringilla@pretium.fi",
			"MainUrl": "http://www.pretium.fi"
		},
		"SendTendersOption": 1,
		"ElectronicAddressToSendTenders": "https://fooo.bar/asdf",
		"ElectronicCommunicationRequiresSpecialTools": false
	},
	"ComplementaryInformation": {
		"IsRecurringProcurement": false,
		"Defence": {
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	},
	"ConditionsInformationDefence": {
		"DepositsRequired": [],
		"FinancingConditions": [],
		"LegalFormTaken": [],
		"OtherParticularConditions": [],
		"PersonalSituationOfEconomicOperators": [
			"Vivamus ac faucibus massa. Morbi pulvinar cursus turpis at cursus."
		],
		"EconomicCriteriaOfEconomicOperators": [
			"Vivamus ac faucibus massa. Morbi pulvinar cursus turpis at cursus."
		],
		"TechnicalCriteriaOfEconomicOperatorsMinimum": [
			"Vivamus ac faucibus massa. Morbi pulvinar cursus turpis at cursus."
		],
		"RestrictedToShelteredWorkshops": false,
		"RestrictedToShelteredProgrammes": false,
		"RestrictedToParticularProfession": false,
		"StaffResponsibleForExecution": false
	},
	"ContactPerson": {
		"Email": "fringilla@pretium.fi"
	},
	"LotsInfo": {
		"DivisionLots": true,
		"QuantityOfLots": 3,
		"LotsSubmittedFor": 1,
		"LotsMaxAwarded": false
	},
	"MainCpvCode": {
		"Code": "35330000",
		"Name": "Ampumatarvikkeet",
		"VocCodes": []
	},
	"ObjectDescriptions": [
		{
			"Title": "Vivamus ac faucibus massa",
			"LotNumber": "1",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Nullam velit nisl, eleifend in ornare id, euismod et nulla. Ut rhoncus elit turpis, quis fringilla tellus semper nec. Duis interdum neque ut enim ultrices ornare. Nam sit amet ligula elit."
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Vestibulum sollicitudin diam enim",
			"LotNumber": "2",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Praesent lacinia, augue eu viverra dignissim, tortor est fermentum sem, vitae gravida lorem elit eget ipsum. Morbi felis sapien, ultricies eu eleifend non, ullamcorper ac neque. Phasellus eu vehicula nunc."
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		},
		{
			"Title": "Integer enim ex, semper id efficitur ut",
			"LotNumber": "3",
			"MainCpvCode": {
				"Code": "35330000",
				"Name": "Ampumatarvikkeet",
				"VocCodes": []
			},
			"AdditionalCpvCodes": [],
			"NutsCodes": [],
			"DescrProcurement": [
				"Suspendisse dui odio, aliquam tempus augue et"
			],
			"AgreeAwardCriteriaToBePublished": true,
			"AwardCriteria": {
				"CriterionTypes": 0
			},
			"AwardContract": null,
			"EstimatedValue": null,
			"TimeFrame": null,
			"CandidateNumberRestrictions": {},
			"OptionsAndVariants": null,
			"TendersMustBePresentedAsElectronicCatalogs": false,
			"EuFunds": {
				"ProcurementRelatedToEuProgram": false
			}
		}
	],
	"Organisation": {
		"Information": {
			"OfficialName": "Lorem ipsum dolor sit amet",
			"NationalRegistrationNumber": "2012703-3",
			"PostalAddress": {
				"StreetAddress": "Nullam velit nisl, eleifend 2324",
				"PostalCode": "00002",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"Email": "fringilla@pretium.fi",
			"MainUrl": "http://www.pretium.fi"
		},
		"ContractingAuthorityType": 2,
		"MainActivity": 4
	},
	"Project": {
		"ContractType": 1,
		"Title": "Fusce sodales bibendum sodales",
		"ProcurementCategory": 2,
		"JointProcurement": false,
		"DefenceSupplies": 0
	},
	"PublishToTed": false,
	"ShortDescription": [
		"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque commodo feugiat diam ac faucibus. Sed sagittis eu quam id ornare. Morbi congue odio velit, rutrum feugiat sem luctus quis. Phasellus hendrerit nulla iaculis metus rhoncus laoreet. Ut eu finibus enim. Nam ultricies tortor quis nunc hendrerit vehicula. Suspendisse vestibulum elit quis mi viverra, id accumsan augue rhoncus. Sed quis turpis ut nisl ultrices vehicula. Fusce in posuere eros.",
		"",
		"In ac tortor nec ipsum ultricies pellentesque vel sollicitudin magna. Suspendisse dictum augue sed augue efficitur pellentesque. Aliquam nec lectus tellus. Mauris consectetur metus nec consectetur eleifend. Phasellus pharetra laoreet eros, sed sagittis libero dictum non. Proin elementum eget nisl ornare aliquet. Nunc iaculis, metus et bibendum congue, lorem risus bibendum leo, eu pretium tortor orci sit amet lacus. Duis tristique sapien nec metus sollicitudin tristique. Sed eu accumsan massa, vitae tincidunt ligula. ",
		"Praesent lacinia, augue eu viverra dignissim, tortor est fermentum sem, vitae gravida lorem elit eget ipsum. Morbi felis sapien, ultricies eu eleifend non, ullamcorper ac neque. Phasellus eu vehicula nunc. Fusce sodales bibendum sodales. Nam consectetur orci vitae neque placerat dictum. In id ex quis ex molestie volutpat ut nec mi. Aliquam ac aliquam nunc. Nullam a augue finibus, luctus felis egestas, facilisis turpis. Duis lobortis vestibulum massa. Etiam placerat condimentum mi ac facilisis. Aliquam erat volutpat. Mauris odio ipsum, molestie at egestas non, eleifend eget orci.",
		"",
		"Vestibulum sollicitudin diam enim, vel ullamcorper neque ultrices eu. Praesent orci elit, euismod nec suscipit a, auctor et quam. Integer libero augue, dictum et ante volutpat, sodales interdum urna. Vivamus tempor congue felis, in mollis ante accumsan at. Curabitur ultricies imperdiet placerat. Aenean consequat mi sed dolor egestas, at lobortis mauris scelerisque. Vestibulum sed accumsan libero. Donec efficitur, dui eu eleifend auctor, erat sapien finibus est, ut egestas neque dolor eget nisl. Ut vitae tortor erat.",
		"",
		"Integer enim ex, semper id efficitur ut, efficitur scelerisque ante. Donec egestas magna sit amet metus varius venenatis. Integer consequat magna in lobortis pulvinar. Suspendisse dui odio, aliquam tempus augue et, pharetra volutpat augue. Aliquam erat volutpat. In lorem massa, vehicula non facilisis id, posuere vel tortor. Nulla facilisi. Nunc faucibus dolor ut ante efficitur, et ultrices elit feugiat. Nulla pharetra hendrerit velit. Proin sagittis, quam non hendrerit commodo, lacus turpis bibendum eros, vel scelerisque quam ex sed nisl."
	],
	"Type": 1700,
	"TenderingInformation": {
		"TendersOrRequestsToParticipateDueDateTime": "2020-03-22T13:00:00",
		"TenderOpeningConditions": {}
	},
	"Language": "FI",
	"ProcedureInformation": {
		"ProcedureType": 2,
		"ElectronicAuctionWillBeUsed": false,
		"Defence": {
			"CandidateNumberRestrictions": {},
			"AwardCriteria": {
				"CriterionTypes": 2,
				"EconomicCriteriaTypes": 8
			}
		}
	},
	"ProceduresForReview": {
		"ReviewBody": {
			"OfficialName": "Markkinaoikeus",
			"PostalAddress": {
				"StreetAddress": "Radanrakentajantie 5",
				"PostalCode": "00520",
				"Town": "Helsinki",
				"Country": "FI"
			},
			"TelephoneNumber": "+358 295643300",
			"Email": "markkinaoikeus@oikeus.fi",
			"MainUrl": "http://www.oikeus.fi/markkinaoikeus"
		}
	},
	"Defence": {
		"NutsCodes": [],
		"Subcontract": {
			"TendererHasToIndicateShare": true,
			"TendererHasToIndicateChange": true,
			"CaMayOblige": false,
			"SuccessfulTenderer": false,
			"SuccessfulTendererMin": 0.0,
			"SuccessfulTendererMax": 0.0,
			"SuccessfulTendererToSpecify": true
		},
		"OptionsAndVariants": {
			"VariantsWillBeAccepted": false,
			"Options": false,
			"OptionType": 0,
			"OptionsDays": 0,
			"OptionsMonths": 0
		},
		"TotalQuantityOrScope": {
			"Type": 2,
			"Currency": "EUR",
			"MinValue": 7700000.0,
			"MaxValue": 9900000.0
		},
		"TotalQuantity": [
			"In eget tincidunt felis. Morbi vel erat id orci vestibulum commodo. Ut eu eros et odio feugiat vehicula. Nullam at sollicitudin nulla. Integer lacinia lectus tortor, ac faucibus quam laoreet at. Quisque vestibulum, nulla vel auctor porta, lacus enim porta enim, et euismod lacus tellus vel arcu. Donec dolor magna, ullamcorper sit amet turpis in, blandit malesuada nisl. Mauris volutpat nibh sed luctus tincidunt."
		],
		"Renewals": {}
	},
	"IsCorrigendum": false,
	"ContractAwardsDefence": null
}
```

**Expected behavior**
In 200 OK response POST should give TED XML.
PUT should not result in 500 Internal Server Error.

**API response**
What is the response from Hilma API? Include the response headers and timestamps.
POST response:
Response status

200 OK
Response latency
340 ms
Response content

Pragma: no-cache
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Wed, 19 Feb 2020 13:30:44 GMT
Content-Length: 0

PUT response:
500 Internal Server Error
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Date: Wed, 19 Feb 2020 11:06:15 GMT  

**Additional context**

**Comment by jannef** [comment] 2020-02-20 06:42
Issue is under investigation.

81/2009/EY based notices (ie. the defense notice family) are known to have very quirky XSD validation and extra care needs to be taken when forming these requests.

**Comment by jannef** [comment] 2020-02-20 07:00
There seems to be an issue with the notice contents.

Organisation.Information.NutsCodes seems to be missing, please supply an empty array instead of null.

The error takes place when data is being committed and violates a constraint, and is thus not triggered by the POST testing endpoint.

I've added an issue to the backlog about the issue.

**Comment by cloudia-jt** [comment] 2020-02-20 07:35
What do you mean "Organisation.Information.NutsCodes seems to be missing". Your documentation for [TED F17](https://www.hankintailmoitukset.fi/fi/documentation/1700) states that Organisation.Information does not contain NutsCodes.

**Comment by jannef** [comment] 2020-02-20 11:13
The issue is caused by different default value for string[] in C# 7.1 (API implementation) and type/ecmascript (documentation implementation), which causes an error to occur when there is no default value set for auto property, which in turn is mapped to constrained column by EF.

The mentioned fix will a) set a default value and b) catch such exception and return a sensible hint. Sending an empty array allows you to work around the issue while the fix is pending.

**Comment by jannef** [comment] 2020-02-20 11:54
After the fix, the API would return following response in similar situation.

```
400 Bad Request
There was unexpected value in the model. This is an error with the ETS API, please report this issue. Hint to self diagnose the violating field: Organisations.Information.NutsCodes
```

However, the given sample now works, as the the default value will be set correctly for that field.

**Closed** 2020-02-24 09:57 UTC
Labels: Pending deployment
