### ISSUE TITLE
Publishing notices gives ServiceUnavaible sometimes

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#107] opened 2021-05-31 07:56 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
timestamps:

2021-05-31 10:29:40.873
2021-05-31 09:20:09.597

**Comment by brianshdk** [comment] 2021-05-31 13:41
We're seing the same:

31-05-2021 14:32	<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0Rde0YAAAAACpFI/2seL0RKdvVQneLlbuQlJVMzBFREdFMDcwNgAwMTEzMDRiZi1jMzE2LTQ1YTAtYWVhOC0xYWQwMGMyZTZiMjc=</span></div></div></body></html>

**Comment by jannef** [comment] 2021-05-31 15:01
This error message is emitted by Azure Frontdoor. We will investigate the reason for this service degregation.

**Comment by jannef** [comment] 2021-06-01 05:50
A part of code has been identified that causes database utilization to shoot up to 100%, which causes some services becoming unresponsive; degregation of ETS API is likely because of this.

The issue is now worked on, and hotfix will be released as soon as possible.

**Comment by jannef** [comment] 2021-06-01 13:40
The fix is now live in production. There was an API method used by the public notice view, that was fetching notices using sub-optimal predicate.

**Closed by jannef** 2021-06-01 13:40 UTC
