### ISSUE TITLE
Notice published in ted but not in hilma

### ISSUE THREAD

**Issue by anttiremes** [Hankintailmoitukset/hilma-api#73] opened 2020-11-13 06:41 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
https://ted.europa.eu/udl?uri=TED:NOTICE:537849-2020:TEXT:FI:HTML&src=0

notice was sended to Hilma 5.11

Api response 

service unavaible

**Comment by jannef** [comment] 2020-11-13 07:23
There seems to be ongoing issue, that causes notices to be sent to TED again, resulting in rejection due "Duplicate NO_DOC_EXT, a notice with the same identifier has already been received.". This sets the notice in error state in Hilma.

Investigating.

**Comment by jannef** [comment] 2020-11-13 08:09
On the first look, it seems like the Ets-api emits the message to TED twice, if the same notice is PUT twice in rapid succession.

The second request is returning bad request due incorrect status, but for some reson the message is getting put to service bus.

This might be related to the other outstanding issue, where the api some times times out.

While the fix is pending, increasing the waiting time on your retry policy should prevent this from happening.

**Comment by jannef** [comment] 2020-11-13 08:43
The notice in question can now be found in Hilma:
https://www.hankintailmoitukset.fi/fi/public/procurement/43358/notice/57725/overview

Several other affected notices are also fixed.

**Comment by jannef** [comment] 2020-11-16 11:56
Fix for this issue is now deployed in koulutus-environment.

Moving forward, only one concurrent request may modify the same notice at once. While the notice is "locked" for editing by another request, subsequent requests will recieve 409 response.

However, I identified another issue, that may result in a similar error state: notices publication of which is cancelled in TED are returned to draft state in Hilma. Sending such notice again would result in the same Duplicate NO_DOC_EXT-issue. These notices should be set to NotPublic=8 state and edits to these should be outright rejected.

The severity of the other discovered issue is low, as it only affects notices that are not published and can never become published. While the fix is pending, do not attempt to re-send notices publication of which is cancelled.

**Comment by anttiremes** [comment] 2020-11-20 06:11
Same problem notice: etsidfixed_35285

**Comment by anttiremes** [comment] 2020-11-20 06:15
And production_37205

**Comment by jannef** [comment] 2020-11-20 08:36
Etsidfixed_35285 is not suffering from this issue, but the cause is different: the original notice was rejected with reason code DU (duplicate of 2020-058469; https://www.hankintailmoitukset.fi/fi/public/procurement/42576/notice/58469/overview). The other ongoing issue pending installing the fixed allowed resending this notice (Etsidfixed_35285), when it should not be allowed. Please dot not attempt to send Etsidfixed_35285 again.

**Comment by jannef** [comment] 2020-11-20 08:39
production_37205 was affected by this issue and is now manually fixed.

**Comment by jannef** [comment] 2020-11-24 06:32
A fix for this issue was installed 23.11.2020, around 15:30

**Closed** 2020-11-25 08:24 UTC
