### ISSUE TITLE
Award notice given parent appears to have changed

### ISSUE THREAD

**Issue by cloudia-jt** [Hankintailmoitukset/hilma-api#6] opened 2020-01-29 13:10 UTC
**ATTENTION!** Fill in the following information but **DO NOT** include any non-public information such as API keys or actual notice data.

**Describe the bug**
When trying to publish award notice error message "Given parent appears to have changed. Please supply the original parent identifier or leave it blank." given even though parent is for the original contract notice.

**To Reproduce**
https://api.hankintailmoitukset.fi/ets/external-api/v1/notice/etsidfixed_2575?parentId=2018-025124&projectId=9139
check email for the payload

**Expected behavior**
No error about the changed parent.

**API response**
BadRequest response headers:
Pragma: no-cache
Transfer-Encoding: chunked
Request-Context: appId=cid-v1:1c7c1805-f4ec-49e2-a8f3-5993b60c63f5
Cache-Control: no-store, no-cache
Date: Wed, 29 Jan 2020 11:38:34 GMT  

Given parent appears to have changed. Please supply the original parent identifier or leave it blank. Re-parenting is not allowed. Please create a new notice if the parent is wrong.

**Additional context**
It seems that https://www.hankintailmoitukset.fi/fi/public/procurement/9139/notice/14396 order is messed up.

**Comment by jannef** [comment] 2020-02-04 08:50
Duplicate of #11 

The given notice you are trying to PUT is already present in the database with null parent. This is considered parenting. Please follow the advice in the linked issue.

**Closed by jannef** 2020-02-04 08:50 UTC
