### ISSUE TITLE
Notice validation - change notice

### ISSUE THREAD

**Issue by OlliSurakka** [Hankintailmoitukset/hilma-api#205] opened 2023-12-15 12:06 UTC
In test environment: https://testi.hankintailmoitukset.fi/fi/preview/procedure/11756/enotice/13576/

Test notice Testihankinta15122023_Eliite is published. The user has created a new notice to make changes to this notice. Notice has been created to test environment as a draft through SC Software API.

**To Reproduce**
- Testnotice Testihankinta15122023_Eliite is published. 
- The user has created a new notice to make changes to this notice. Notice has been created to test environment as a draft through SC Software API.
- All mandatory fields are filled and the user wants to publish the new notice with changes.
- In the preview the notice can't be published because of validation errors. (Image)
- The same problem occurred also earlier https://testi.hankintailmoitukset.fi/fi/preview/procedure/11162/enotice/12995/. (image)

![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/04a1b39a-4860-4eb0-800e-e11072ba976e)

![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/b9ecce0d-81a4-4594-bdfa-894032e05acb)

**Expected behavior**
The validation is ok and the user can publish the notice.

**Comment by JuhaHakli** [comment] 2023-12-22 08:21
I'll start looking into this. I'll inform you on the progress.

**Comment by JuhaHakli** [comment] 2023-12-29 08:04
There had been a bug earlier about the fields that this is concerning, but the fix was not yet pushed to test. I was unable to recreate the problem using the new release and the data you have in these notices. Could you try again, now that test has been updated with latest fixes?

If you get the same problem again, then please also send the post-body, so we can recreate the steps more accurately.

**Comment by Havunen** [comment] 2024-01-24 10:14
The test environment has been updated, are you still experiencing this issue?

**Comment by OlliSurakka** [comment] 2024-01-29 13:03
Tested this several times and the following validation problem appears.

https://testi.hankintailmoitukset.fi/fi/preview/procedure/13632/enotice/15534/

![image](https://github.com/Hankintailmoitukset/hilma-api/assets/146176930/fec9d939-3449-4a80-99f2-3615853f9707)

The following steps are needed to create the problem:
- Notice has been created to test environment as a draft through API.
- All mandatory fields are filled and the user wants to publish the notice
- The user opens the preview 
- The notice can't be published because of validation errors.
- The user goes back to modify notice but doesn't change anything.
- The user goes back to preview -> No more validation problems.

**Comment by Havunen** [comment] 2024-02-16 12:02
@OlliSurakka 

Can you provide us the body for the draft notice please

**Comment by Havunen** [comment] 2024-02-21 05:43
@OlliSurakka 

Does this issue reproduce constantly with some draft notice or was it something that happened once? The fix what Juha did previously was so that it fixes the data once the user opens the problematic page, but it shouldn't reproduce anymore at least I cannot reproduce it. As the data gets fixed once user fills the page

**Comment by OlliSurakka** [comment] 2024-02-22 07:58
We are experiencing this issue constantly (first publication, publication with changes to original notice, award notice). 

Enclosed are data sent to API and data read from API, when draft notice is filled in Hilma.
[sent.json](https://github.com/Hankintailmoitukset/hilma-api/files/14370668/sent.json)
[read.json](https://github.com/Hankintailmoitukset/hilma-api/files/14370669/read.json)

**Comment by Havunen** [comment] 2024-02-26 08:19
@OlliSurakka 

I still cannot reproduce the issue, What else needs to be done than sending the draft notice through API ( as in sent.json ) and filling the notice and publishing it? I tried creating change notice and CAN from that notice but it does not reproduce the problem :/

**Comment by Havunen** [comment] 2024-03-07 05:52
The fix is in production

**Closed by Havunen** 2024-03-07 05:52 UTC
