### ISSUE TITLE
Test environment and staging environment cross posting

### ISSUE THREAD

**Issue by jaandk** [Hankintailmoitukset/hilma-api#42] opened 2020-05-12 12:01 UTC
When publishing a notice to https://hns-hilma-staging-apim.azure-api.net and the afterwards try to get the status. 

Request: https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/86026277
Responce: No such Notice etsId=86026277

Request:  https://hns-hilma-test-apim.azure-api.net/ets/external-api/v1/notice/86026277
Responce: I get the status for the tender

It is like that publish requests are routed to test and not staging, but all other requests are hitting the staging environment?
I would expect the Test and Staging to be different databases?

**Comment by jannef** [comment] 2020-05-14 09:48
The issue reported is now under investigation.

**Comment by jannef** [comment] 2020-05-14 10:10
I am unable to reproduce the issue and require more information. Could you attach the http response including the headers (as shown below) from the PUT action for a notice that can't be found?

Reponse for my PUT:
```
HTTP/1.1 201 Created

cache-control: no-store,no-cache
content-type: application/json; charset=utf-8
date: Thu, 14 May 2020 10:01:58 GMT
location: http://hns-hilma-staging-api-wapp.azurewebsites.net/external-api/v1/notice/staging-janne-0001
pragma: no-cache
request-context: appId=cid-v1:60071d4c-cdb6-420c-9fe4-6e9d212ede47
transfer-encoding: chunked
x-azure-ref: 0Fhe9XgAAAACOOtHBFmZ8TrniS6UN5Nc6QlJVMzBFREdFMDQyMAA1ODEwZWQ3Ni0xODAzLTQ2ZDMtYWM2Yy0wZWRjZDgyNDFmY2E=

{
    "noticeNumber": "2020-029456",
    "creationDate": "2020-05-14T10:01:58.3248846Z",
    "modificationDate": "2020-05-14T10:01:58.5308186Z",
    "hilmaStatus": 2,
    "hilmaPublicationDate": "2020-05-14T10:01:58.5292551Z",
    "etsIdentifier": "staging-janne-0001",
    "organisationId": "3541577-5",
    "projectId": 23669,
    "noticeId": 29456,
    "tedStatus": 0
}
```

GET Request
```
GET https://hns-hilma-staging-apim.azure-api.net/ets/external-api/v1/notice/staging-janne-0001?includeNotice=False HTTP/1.1

Cache-Control: no-cache
Ocp-Apim-Subscription-Key: 21ce5459b70e4dd98301ee115cfd266e
```


GET response
```
HTTP/1.1 200 OK

cache-control: no-store,no-cache
content-type: application/json; charset=utf-8
date: Thu, 14 May 2020 10:03:42 GMT
pragma: no-cache
request-context: appId=cid-v1:60071d4c-cdb6-420c-9fe4-6e9d212ede47
transfer-encoding: chunked
x-azure-ref: 0fhe9XgAAAAAIHXs5S/DdT73x4oxQJ2BFQlJVMzBFREdFMDQyMAA1ODEwZWQ3Ni0xODAzLTQ2ZDMtYWM2Yy0wZWRjZDgyNDFmY2E=

{
    "noticeNumber": "2020-029456",
    "creationDate": "2020-05-14T10:01:58.3248846",
    "modificationDate": "2020-05-14T10:01:58.5308186",
    "hilmaStatus": 2,
    "hilmaPublicationDate": "2020-05-14T10:01:58.5292551",
    "etsIdentifier": "staging-janne-0001",
    "organisationId": "3541577-5",
    "projectId": 23669,
    "noticeId": 29456,
    "tedStatus": 0
}

```

**Comment by jannef** [comment] 2020-05-19 08:23
Closing the issue as there is no follow-up.

**Closed by jannef** 2020-05-19 08:23 UTC
Labels: question
